version: "3.8"
services:
  watcher:
    image: ghcr.io/oktupol/latex-watcher:1.0
    environment:
      WATCH_MODE: "true"
    volumes:
      - ./source:/opt/watcher/source
      - ./destination:/opt/watcher/destination
      - cache:/opt/watcher/cache
volumes:
  cache:
    driver: local
